title: Mengzhe Wang's Homepage
page-top-title: Mengzhe Wang
top-section-bg-text: Embodied AI & Computer Vision
home-subtitle: Undergraduate in Intelligent Science and Technology @ Fudan University
copyright-text: '&copy; Mengzhe Wang 2022-2026. All Rights Reserved.'